add support for timescaleDB according to issue #1668
mindsdb/datasources pull request #38
Opened 2021-10-22 09:52 UTC by Ashutosh619-sudo

added support for timescaleDB in mindsdb data source according to issue #1668.

2021-10-22 11:50 UTC, StpMax requested changes
also need add import of this class to `__init__.py`

2021-10-22 11:50 UTC, StpMax commented on mindsdb_datasources/datasources/timescale_ds.py
> +import os
unnecessary import

2021-10-22 18:05 UTC, Ashutosh619-sudo commented on mindsdb_datasources/datasources/timescale_ds.py
> +import os
On it.

2021-10-22 18:11 UTC, Ashutosh619-sudo commented on mindsdb_datasources/datasources/timescale_ds.py
> +import os
done all the changes!

2021-10-25 10:22 UTC, ZoranPandovski approved these changes
Thanks

2021-10-25 10:22 UTC, merged