Bigquery data source
mindsdb/datasources pull request #40
Opened 2021-10-23 16:04 UTC by ktyborowski

A simple Google BigQuery data source implementation. 
Fixes mindsdb/mindsdb#1680]

The test assumes that the `GOOGLE_APPLICATION_CREDENTIALS`  variable is set in the test environment. This could be changed to support the `DB_CREDENTIALS` setup. As this would require addditional steps with the google-auth library I thougt this should be consulted so I left the test with inferred credentials.

The test is using a very simple BigQuery public dataset. This could also be changed to any other [public dataset](https://cloud.google.com/bigquery/public-data).

2021-10-25 10:26 UTC, ZoranPandovski requested changes
Awesome. Please just add the BigQueryDS to the __init__ file

2021-10-25 14:36 UTC, ZoranPandovski commented
Can you merge staging please and resolve the conflict?

2021-10-25 16:43 UTC, ktyborowski commented
Resolved the conflict. Could you verify that I did that correctly?

2021-10-26 12:40 UTC, ZoranPandovski approved these changes

2021-10-26 12:40 UTC, merged