Dremio datasource
mindsdb/datasources pull request #41
Opened 2021-10-24 16:41 UTC by ktyborowski

Fixes mindsdb/mindsdb#1685

Initial implementation of the Dremio datasource.

What has been done:

1. Created and initial implementation of Dremio datasource based on the existing snowflake datasource and Dremio docs.
2. Added a very simple test boilerplate. This requires a Dremio instance with a database so for now I left the rest for discussion.

2021-10-25 10:31 UTC, ZoranPandovski requested changes

2021-10-25 10:31 UTC, ZoranPandovski commented on mindsdb_datasources/datasources/dremio_ds.py
> +import pyodbc
Can you please add this to the requirements?

2021-10-25 10:31 UTC, ZoranPandovski commented on mindsdb_datasources/datasources/dremio_ds.py
> +class DremioDS(SQLDataSource):
Please add this to __init__.py

2021-10-25 10:31 UTC, ZoranPandovski commented on mindsdb_datasources/datasources/dremio_ds.py
> +                 driver='Dremio ODBC Driver 64-bit', port=31010):
Maybe you can add warning in the __init__ py same as we did for snowflake, that driver is required

2021-10-25 13:37 UTC, ktyborowski commented on mindsdb_datasources/datasources/dremio_ds.py
> +import pyodbc
I added information about the requirement to the init notification as that's how it's done in the snowflake_ds. If you would prefer this to be in the requirements let me know.

2021-10-25 13:38 UTC, ktyborowski commented on mindsdb_datasources/datasources/dremio_ds.py
> +class DremioDS(SQLDataSource):
Added.

2021-10-25 13:39 UTC, ktyborowski commented on mindsdb_datasources/datasources/dremio_ds.py
> +                 driver='Dremio ODBC Driver 64-bit', port=31010):
Done, also added pyodbc requirement to the notification as it's done in the snowflake_ds.

2021-10-26 12:41 UTC, ZoranPandovski approved these changes

2021-10-26 12:46 UTC, merged