Adding presto data source
mindsdb/datasources pull request #42
Opened 2021-10-24 19:21 UTC by MichaelLantz

Fixes mindsdb/mindsdb#1689

## Please describe what changes you made, in as much detail as possible
  - Adding datasource for Presto
  - Adding test against Presto datasource
  - Adding initialization check for Presto datasource
  - Updating dependencies / requirements for new presto python library

datasources

2021-10-24 19:25 UTC, MichaelLantz commented
Still attempting to get my local tests working since all but file data sources test fail but the core of the data source has been created.

2021-10-25 10:34 UTC, ZoranPandovski requested changes

2021-10-25 10:34 UTC, ZoranPandovski commented on mindsdb_datasources/__init__.py
> +    print("PrestoDS is not available by default. Please install snowflake's ODBC driver and pyodbc to use it!")
Please change the snowflake message

2021-10-25 10:34 UTC, ZoranPandovski commented on mindsdb_datasources/datasources/presto_ds.py
> +        df = pd.read_sql(q, con=con)
Why we need pandas here?

2021-10-25 10:34 UTC, ZoranPandovski commented on mindsdb_datasources/datasources/presto_ds.py
> +        con.close()
We need to close the connection last

2021-10-26 16:20 UTC, ZoranPandovski commented
****CLA Assistant Lite bot**** All contributors have signed the CLA  ✍️

2021-10-26 18:53 UTC, MichaelLantz commented
I have read the CLA Document and I hereby sign the CLA

2021-10-27 12:30 UTC, ZoranPandovski approved these changes

2021-10-27 12:30 UTC, merged