Solr datasource
mindsdb/datasources pull request #43
Opened 2021-10-24 19:23 UTC by ktyborowski

This is an implementation for Apache Solr as a data source. It's based on a JDBC connection and python JayDeBeApi.

Thought it might be nice to have a direct connection to Solr inside MindsDB. Solr in some cases has it's own SQL syntax so this should be considered. This implementation also assumes that the solr jdbc connector is in the CLASSPATH. Java also needs to be installed in the environment.

No tests added for now as the idea of a Solr datasource needs to be discussed with the maintainers. The tests could use a base Solr installation though, as it comes with a default collection to query against.

Changes:

1. Added a Solr datasource
2. Added JayDeBeApi to requirements.txt

If this gets approved it would be nice if it counted towards the hacktoberfest goal 😄

2021-10-25 10:37 UTC, ZoranPandovski requested changes

2021-10-25 10:37 UTC, ZoranPandovski commented on mindsdb_datasources/datasources/solr_ds.py
> +class SolrDS(SQLDataSource):
Please just add this to __init__ py

2021-10-25 10:39 UTC, ZoranPandovski requested changes

2021-10-25 10:39 UTC, ZoranPandovski commented on requirements.txt
> +JayDeBeApi 1.2.3
Will this work without == ?

2021-10-25 12:22 UTC, ktyborowski commented on requirements.txt
> +JayDeBeApi 1.2.3
Hey, I looked into snowflake datasource implementation and changed accordingly. For now I have removed the requirements and added information in the init. The init info includes the jaydebeapi , the solr install and the classpath export requirements. 

One more thing with the classpath exporting is that it is possible to give the path to the JDBC driver jar. Would you like to add an optional parameter for that? If this parameter is not set the Solr datasource could fallback to the CLASSPATH variable.

2021-10-25 13:40 UTC, ktyborowski commented on mindsdb_datasources/datasources/solr_ds.py
> +class SolrDS(SQLDataSource):
Added.

2021-10-26 16:21 UTC, ZoranPandovski commented
****CLA Assistant Lite bot**** All contributors have signed the CLA  ✍️

2021-10-26 16:33 UTC, ktyborowski commented
Responding to the CLA agreement.

I have read the CLA Document and I hereby sign the CLA.

2021-10-27 12:32 UTC, ZoranPandovski commented
@pixpack Please just respond with `I have read the CLA Document and I hereby sign the CLA.` otherwise the bot will not be triggered :)

2021-10-27 14:49 UTC, ktyborowski commented
I have read the CLA Document and I hereby sign the CLA.

2021-10-27 15:00 UTC, merged